Repository atlassian/github-for-jira, pull requests merged in 2021-05, with the labels that each got.

#441 ARC-103 change ACTIVE to IN PROGRES
  SUPPORT.md
  lib/frontend/get-jira-configuration.js
  lib/models/subscription.js
  views/jira-configuration.hbs
Labels: RolloutRisk:Low, enhancement

#437 ARC-114: Allow bots to trigger changes
  lib/github/middleware.js
  test/fixtures/pull-request-triggered-by-bot.json
  test/safe/pull-request.test.js
Labels: RolloutRisk:Low, bug

#447 ARC-116: add PR reviewers in development view
  lib/github/index.js
  lib/github/pull-request.js
  lib/transforms/pull-request.js
  package-lock.json
  package.json
  test/fixtures/api/transform-pull-request-list.json
  test/safe/pull-request.test.js
  test/unit/transforms/pull-request.test.js
Labels: RolloutRisk:Low, bug

#453 ARC-157 fix styling bug
  lib/frontend/app.js
  static/css/jira-configuration.css
  views/jira-configuration.hbs
Labels: RolloutRisk:None, bug

#457 HOTFIX ARC-116: adding logging of payload
  lib/github/pull-request.js
Labels: RolloutRisk:None, enhancement

#435 ARC-102 postlogin redirect
  .gitignore
  CONTRIBUTING.md
  lib/frontend/app.js
  lib/frontend/get-github-configuration.js
  lib/frontend/get-github-login.js
  lib/frontend/github-oauth.js
  package-lock.json
  static/js/jira-configuration.js
Labels: RolloutRisk:High, enhancement

#456 ARC-118 support merge commits
  lib/transforms/push.js
  test/fixtures/push-merge-commit.json
  test/fixtures/push-non-merge-commit.json
  test/safe/push.test.js
Labels: RolloutRisk:Low, enhancement

#452 ARC-75 update paginate promise to use endpoint instead
  lib/sync/discovery.js
Labels: RolloutRisk:None, enhancement

#451 ARC-92 sort repos by updated_at
  lib/sync/installation.js
  lib/sync/jobs.js
  test/fixtures/repo-sync-state.json
  test/fixtures/sorted-repos.json
  test/unit/sync/helpers/sync-helpers.test.js
Labels: RolloutRisk:Low, enhancement

#459 Disturbed - fix doc typos
  CONTRIBUTING.md
  README.md
  docs/legacy-features.md
  docs/permissions.md
Labels: RolloutRisk:None

#454 ARC-74 fix for error sending the complete event to Jira
  lib/api/index.js
  lib/jira/client/index.js
  lib/jira/util/isProd.js
  lib/sync/installation.js
  test/unit/api/__snapshots__/api.test.js.snap
  test/unit/api/api.test.js
Labels: RolloutRisk:Low, bug

#405 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: RolloutRisk:None
